import { ArrowRight, BookOpen, Feather, Heart, Sparkles } from "lucide-react";
import { Link } from "wouter";
import { programs } from "../data/siteData";
import { Doodle, StorybookIllustration } from "../components/Illustrations";
import { ProgramCard, SectionHeading } from "../components/ContentBlocks";
import FeaturedVideo from "../components/FeaturedVideo";
import QuizAdventure from "../components/QuizAdventure";

export default function Home() {
  return <>
    <section className="relative overflow-hidden border-b border-[#e8ddc6] px-4 pb-16 pt-36 sm:px-8 sm:pb-24 sm:pt-44 lg:pb-28"><div className="container relative grid items-center gap-10 lg:grid-cols-[.92fr_1.08fr] lg:gap-4"><div className="relative z-10 max-w-2xl"><div className="mb-7 inline-flex items-center gap-2 rounded-full border border-[#e8ddc6] bg-[#fffdf5]/75 px-4 py-2 text-[.7rem] font-900 uppercase tracking-[.15em] text-[#7f765f]"><span className="h-2 w-2 rounded-full bg-[#8dbf8a]" /> A creative learning space for curious children</div><h1 className="max-w-[720px] text-[clamp(3.35rem,8vw,7.2rem)] font-600 leading-[.88]">Where little readers become <span className="relative inline-block text-[#ef7e72]">big storytellers<span className="absolute -bottom-3 left-1/4 h-2 w-3/4 rotate-[-2deg] rounded-full bg-[#f9d96b]" /></span>.</h1><p className="mt-8 max-w-xl text-base leading-7 text-[#6d7b80] sm:text-lg sm:leading-8">Creative writing, storytelling, vocabulary and language adventures designed to help young minds <strong className="font-800 text-[#43545a]">imagine, express and create.</strong></p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/programs" className="inline-flex items-center justify-center rounded-full bg-[#263238] px-6 py-4 text-sm font-900 text-[#fff9e8] shadow-[4px_5px_0_#f58f82] transition-all hover:-translate-y-1 hover:shadow-[6px_7px_0_#f58f82]">Explore Programs <ArrowRight size={18} className="ml-2" /></Link><Link href="/contact" className="inline-flex items-center justify-center rounded-full border-2 border-[#263238] px-6 py-4 text-sm font-900 text-[#263238] transition-colors hover:bg-[#f9d96b]">Book a Trial</Link></div></div><div className="relative lg:pl-6"><span className="float-gently absolute left-[7%] top-[12%] z-10 rotate-[-14deg] text-[#ef7e72]"><Doodle type="star" size={34} /></span><span className="float-gently-delayed absolute right-[7%] top-[23%] z-10 rotate-[16deg] text-[#3d7042]"><Doodle type="leaf" size={35} /></span><span className="absolute bottom-[6%] left-[9%] z-10 rotate-[-12deg] text-[#25677c]"><Doodle type="feather" size={32} /></span><StorybookIllustration /></div></div><div className="container mt-8 flex items-center gap-4 text-[.68rem] font-900 uppercase tracking-[.18em] text-[#9b8b68] sm:mt-0"><span className="h-px w-12 bg-[#f58f82]" />Learning doesn’t have to feel like studying<span className="h-px flex-1 bg-[#e8ddc6]" /></div></section>
    <section className="storybook-section py-16 sm:py-24"><div className="container grid gap-10 lg:grid-cols-[1fr_.85fr] lg:items-center"><div><SectionHeading eyebrow="The why behind the work" title="A thoughtful place for growing minds." text="Stories give children room to imagine, express and think. We make space for the interests that help language come alive." /></div><div className="grid gap-4 sm:grid-cols-3"><div className="rounded-2xl border border-[#e8ddc6] bg-[#fffdf5] p-5"><BookOpen className="text-[#8fd3e8]" size={22} /><p className="mt-4 font-[Fraunces] text-xl">Imagine</p><p className="mt-2 text-sm leading-6 text-[#6d7b80]">Ideas begin as sparks, questions and characters.</p></div><div className="rounded-2xl border border-[#e8ddc6] bg-[#fffdf5] p-5"><Feather className="text-[#f4a261]" size={22} /><p className="mt-4 font-[Fraunces] text-xl">Express</p><p className="mt-2 text-sm leading-6 text-[#6d7b80]">Children find words for what they notice.</p></div><div className="rounded-2xl border border-[#e8ddc6] bg-[#fffdf5] p-5"><Heart className="text-[#ef7e72]" size={22} /><p className="mt-4 font-[Fraunces] text-xl">Grow</p><p className="mt-2 text-sm leading-6 text-[#6d7b80]">Confidence grows through sharing and making.</p></div></div></div></section>
    <FeaturedVideo />
    <section className="bg-[#f5efdf] py-16 sm:py-24"><div className="container"><div className="flex flex-col justify-between gap-7 sm:flex-row sm:items-end"><SectionHeading eyebrow="Find their next adventure" title="Programs with room to wonder." text="Choose a starting point, then let curiosity lead the way." /><Link href="/programs" className="inline-flex shrink-0 items-center gap-2 text-sm font-900 text-[#263238] underline decoration-[#ef7e72] decoration-2 underline-offset-4">View all programs <ArrowRight size={17} /></Link></div><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{programs.slice(0, 3).map((program) => <ProgramCard key={program.slug} program={program} compact />)}</div></div></section>
    <section className="paper-lines py-16 sm:py-24"><div className="container grid gap-10 lg:grid-cols-[.75fr_1.25fr] lg:items-center"><div><SectionHeading eyebrow="A tiny personality quiz" title="Choose your adventure." text="Three gentle questions. Four ways into a story. No wrong answers." /><Link href="/quiz" className="mt-7 inline-flex items-center gap-2 text-sm font-900 text-[#263238] underline decoration-[#f9d96b] decoration-2 underline-offset-4">Open the full quiz <ArrowRight size={16} /></Link></div><QuizAdventure preview /></div></section>
    <section className="bg-[#8fd3e8]/55 py-16 sm:py-24"><div className="container grid gap-10 lg:grid-cols-[1fr_1.1fr] lg:items-center"><div><p className="text-xs font-900 uppercase tracking-[.18em] text-[#ef7e72]">Meet the mind behind the circle</p><h2 className="mt-5 text-[clamp(2.6rem,5vw,4.8rem)] font-600 leading-[.95]">A personal, <span className="text-[#ef7e72]">not corporate,</span> space.</h2><p className="mt-5 max-w-xl text-base leading-8 text-[#53636a]">The founder story and photo will live here once provided by the client—so families can meet the person and philosophy behind the work.</p><Link href="/about" className="mt-7 inline-flex items-center gap-2 rounded-full bg-[#263238] px-6 py-4 text-sm font-900 text-[#fff9e8] shadow-[4px_5px_0_#f58f82]">Meet our founder <ArrowRight size={17} /></Link></div><div className="relative rounded-[2rem] bg-[#f9d96b] p-6 sm:p-8"><div className="flex aspect-[4/3] items-center justify-center rounded-[1.5rem] border-2 border-dashed border-[#263238]/25 bg-[#fffdf5]/50 text-center"><Sparkles className="text-[#ef7e72]" size={34} /><span className="ml-3 text-sm font-800 text-[#53636a]">Founder photo placeholder</span></div></div></div></section>
    <section className="py-16 text-center sm:py-24"><div className="container"><h2 className="text-[clamp(2.5rem,5vw,4.8rem)] font-600 leading-[.95]">Ready for their next story?</h2><p className="mx-auto mt-5 max-w-xl text-base leading-7 text-[#6d7b80]">Tell us what your child loves and we can share the most natural first step.</p><Link href="/contact" className="mt-8 inline-flex items-center gap-2 rounded-full bg-[#263238] px-7 py-4 text-sm font-900 text-[#fff9e8] shadow-[4px_5px_0_#f58f82]">Book a Trial <ArrowRight size={17} /></Link></div></section>
  </>;
}
