import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, Award, BookOpen, Check, Clock3, Feather, Sparkles, Star, Trophy } from "lucide-react";
import { Link } from "wouter";
import { badges, levels, playableGames } from "../data/learningGameData";
import { getLevel, getLevelName, readDemoProgress } from "../lib/learningProgress";

export default function LearningProgress() {
  const [progress, setProgress] = useState(readDemoProgress);
  useEffect(() => { const refresh = () => setProgress(readDemoProgress()); window.addEventListener("focus", refresh); return () => window.removeEventListener("focus", refresh); }, []);
  const level = getLevel(progress.totalPoints);
  const levelStart = (level - 1) * 100;
  const levelProgress = Math.min(100, Math.round(((progress.totalPoints - levelStart) / 100) * 100));
  const categories = useMemo(() => Array.from(new Set(playableGames.map((game) => game.category))).map((category) => ({ category, total: playableGames.filter((game) => game.category === category).length, completed: playableGames.filter((game) => game.category === category && progress.completedGames.includes(game.id)).length })), [progress.completedGames]);
  return <div className="paper-lines min-h-[calc(100vh-5rem)] px-4 pb-20 pt-32 sm:px-8 sm:pt-40"><div className="container"><Link href="/learning-zone" className="inline-flex items-center gap-2 text-sm font-900 text-[#6d7b80] hover:text-[#ef7e72]"><ArrowLeft size={16} /> Back to Learning Zone</Link><div className="mt-8 grid gap-6 lg:grid-cols-[.85fr_1.15fr]"><section className="rounded-[2rem] bg-[#263238] p-7 text-[#fff9e8] shadow-[7px_8px_0_#f58f82] sm:p-10"><p className="text-xs font-900 uppercase tracking-[.18em] text-[#f9d96b]">My progress · demo mode</p><h1 className="mt-5 font-[Fraunces] text-5xl font-600 leading-[.95] sm:text-6xl">Keep your <span className="text-[#f9d96b]">story growing.</span></h1><p className="mt-5 max-w-md text-sm leading-7 text-[#fff9e8]/70">This private preview uses session-only activity. A future account system can connect the same structure to saved child progress.</p><div className="mt-8 flex items-end justify-between gap-4"><div><p className="text-xs font-900 uppercase tracking-[.12em] text-[#fff9e8]/55">Current level</p><p className="mt-1 font-[Fraunces] text-3xl">{getLevelName(level)}</p></div><Sparkles className="text-[#f9d96b]" size={35} /></div><div className="mt-6 h-3 overflow-hidden rounded-full bg-[#fff9e8]/15"><div className="h-full rounded-full bg-[#f9d96b] transition-all duration-300" style={{ width: `${levelProgress}%` }} /></div><p className="mt-2 text-xs text-[#fff9e8]/55">{progress.totalPoints - levelStart} / 100 points toward the next level</p></section><section className="grid gap-3 sm:grid-cols-2"><Stat icon={<Star />} label="Points" value={progress.totalPoints} /><Stat icon={<Check />} label="Games completed" value={progress.completedGames.length} /><Stat icon={<Feather />} label="Writing activities" value={progress.writingActivities} /><Stat icon={<Trophy />} label="Badges earned" value={progress.badges.length} /></section></div>

<section className="mt-16"><p className="text-xs font-900 uppercase tracking-[.18em] text-[#ef7e72]">Your learning shelves</p><h2 className="mt-3 font-[Fraunces] text-4xl font-600">Category progress</h2><div className="mt-7 grid gap-4 md:grid-cols-2">{categories.map(({ category, total, completed }) => <article key={category} className="story-card rounded-2xl p-5"><div className="flex items-center justify-between gap-3"><h3 className="font-[Fraunces] text-2xl">{category}</h3><span className="text-sm font-900 text-[#6d7b80]">{completed}/{total}</span></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-[#f5efdf]"><div className="h-full rounded-full bg-[#8dbf8a]" style={{ width: `${total ? (completed / total) * 100 : 0}%` }} /></div><p className="mt-3 text-sm text-[#6d7b80]">{completed ? "Nice work — keep exploring." : "Start your first activity to see your progress."}</p></article>)}</div></section>

<section className="mt-16 grid gap-6 lg:grid-cols-2"><div><div className="flex items-end justify-between gap-4"><div><p className="text-xs font-900 uppercase tracking-[.18em] text-[#ef7e72]">Achievements</p><h2 className="mt-3 font-[Fraunces] text-4xl font-600">Badge shelf</h2></div><Award className="text-[#f4a261]" size={32} /></div><div className="mt-7 grid gap-3">{badges.slice(0, 4).map((badge) => <div key={badge.id} className="flex items-center gap-4 rounded-2xl border border-[#e8ddc6] bg-[#fffdf5] p-4 opacity-70"><span className="grid h-11 w-11 place-items-center rounded-full bg-[#f5efdf] text-[#9b8b68]"><Trophy size={20} /></span><div><p className="font-900">{badge.name}</p><p className="text-xs text-[#6d7b80]">Your first steps toward this badge are waiting.</p></div><Clock3 className="ml-auto text-[#9b8b68]" size={17} /></div>)}</div></div><div><p className="text-xs font-900 uppercase tracking-[.18em] text-[#ef7e72]">Recent activity</p><h2 className="mt-3 font-[Fraunces] text-4xl font-600">Your little wins</h2><div className="mt-7 rounded-2xl border border-dashed border-[#e8ddc6] bg-[#fffdf5]/70 p-7">{progress.attempts.length ? <div className="grid gap-3">{progress.attempts.slice().reverse().map((attempt) => <div key={attempt.id} className="flex items-center gap-3 text-sm"><span className="grid h-9 w-9 place-items-center rounded-full bg-[#8dbf8a]/35"><Check size={16} /></span><span className="font-800">{playableGames.find((game) => game.id === attempt.gameId)?.name ?? "Learning activity"}</span><span className="ml-auto text-[#6d7b80]">+{attempt.points} points</span></div>)}</div> : <><BookOpen className="text-[#f9d96b]" size={28} /><p className="mt-4 font-[Fraunces] text-2xl">Your story is just beginning!</p><p className="mt-2 text-sm leading-6 text-[#6d7b80]">Play a game to begin your learning journey.</p></>}</div></div></section>

<p className="mt-14 text-center text-xs text-[#9b8b68]">Level configuration is prepared for future client-approved thresholds: {levels.length} example levels are available to the account system.</p></div></div>;
}
function Stat({ icon, label, value }: { icon: React.ReactNode; label: string; value: number }) { return <article className="story-card rounded-2xl p-6"><div className="flex items-center justify-between text-[#ef7e72]"><span>{icon}</span><span className="rounded-full bg-[#f5efdf] px-2.5 py-1 text-[.62rem] font-900 uppercase tracking-[.1em] text-[#9b8b68]">Demo</span></div><p className="mt-7 font-[Fraunces] text-4xl">{value}</p><p className="mt-1 text-sm font-800 text-[#53636a]">{label}</p></article>; }
