import { useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, BookOpen, Check, Feather, LockKeyhole, PenLine, Search, Sparkles, Star, Trophy } from "lucide-react";
import { Link } from "wouter";
import LearningGameCard from "../components/LearningGameCard";
import { SectionHeading } from "../components/ContentBlocks";
import { MiniIcon } from "../components/Illustrations";
import { ageOptions, difficultyOptions, etymologyPreview, gradeOptions, learningCategories, learningGames, writingPreview } from "../data/learningZoneData";

export default function LearningZone() {
  const [selectedCategory, setSelectedCategory] = useState("All categories");
  const [selectedDifficulty, setSelectedDifficulty] = useState<(typeof difficultyOptions)[number]>("All levels");
    const [selectedAge, setSelectedAge] = useState<string>(ageOptions[0]);
    const [selectedGrade, setSelectedGrade] = useState<string>(gradeOptions[0]);
  const filteredGames = useMemo(() => learningGames.filter((game) => (selectedCategory === "All categories" || game.category === selectedCategory) && (selectedDifficulty === "All levels" || game.difficulty === selectedDifficulty)), [selectedCategory, selectedDifficulty]);

  return <div className="pt-32 sm:pt-40">
    <section className="relative overflow-hidden border-b border-[#e8ddc6] px-4 pb-16 sm:px-8 sm:pb-24"><div className="container grid gap-10 lg:grid-cols-[1fr_.85fr] lg:items-end"><div><Link href="/" className="mb-8 inline-flex items-center gap-2 text-sm font-900 text-[#6d7b80] transition-colors hover:text-[#ef7e72]"><ArrowLeft size={16} /> Back to the circle</Link><p className="mb-5 text-xs font-900 uppercase tracking-[.18em] text-[#ef7e72]">The Lexicon Circle · Learning Zone</p><h1 className="max-w-4xl text-[clamp(3rem,7vw,6.6rem)] font-600 leading-[.88]">A playful place to <span className="text-[#ef7e72]">practise words.</span></h1><p className="mt-7 max-w-xl text-base leading-8 text-[#6d7b80] sm:text-lg">Explore vocabulary, English, creative writing, words and writing through gentle challenges. The games are being prepared with care.</p></div><div className="relative overflow-hidden rounded-[2rem] bg-[#8fd3e8] p-6 shadow-[7px_8px_0_#263238] sm:p-8"><Sparkles className="absolute right-8 top-7 rotate-12 text-[#25677c]" size={31} /><div className="relative grid min-h-[220px] place-items-center rounded-[1.5rem] border-2 border-dashed border-[#25677c]/35 bg-[#fffdf5]/45 text-center"><div><span className="mx-auto grid h-16 w-16 place-items-center rounded-[20px] bg-[#f9d96b] text-[#263238] shadow-[3px_4px_0_#263238]"><BookOpen size={31} /></span><p className="mt-5 font-[Fraunces] text-2xl font-600">Curiosity lives here.</p><p className="mt-2 text-sm text-[#25677c]">No scores yet · just room to explore</p></div></div></div></div></section>

    <section className="py-16 sm:py-24"><div className="container"><SectionHeading eyebrow="Choose a doorway" title="What would you like to explore?" text="These categories are ready to grow into future learning experiences." /><div className="mt-9 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{learningCategories.map((category) => <button type="button" key={category.label} onClick={() => setSelectedCategory(category.label)} aria-pressed={selectedCategory === category.label} className={`learning-category group flex items-start gap-4 rounded-2xl border p-4 text-left transition-all duration-200 hover:-translate-y-1 ${selectedCategory === category.label ? "border-[#263238] bg-[#fffdf5] shadow-[4px_5px_0_#f9d96b]" : "border-[#e8ddc6] bg-[#fffdf5]/60 hover:bg-[#fffdf5]"}`}><MiniIcon name={category.icon} tone={category.tone} /><span><span className="block text-sm font-900 leading-tight">{category.label}</span><span className="mt-1 block text-xs leading-5 text-[#6d7b80]">{category.description}</span></span></button>)}</div><button type="button" onClick={() => setSelectedCategory("All categories")} aria-pressed={selectedCategory === "All categories"} className={`mt-4 rounded-full border px-4 py-2 text-xs font-900 transition-colors ${selectedCategory === "All categories" ? "border-[#263238] bg-[#263238] text-[#fff9e8]" : "border-[#e8ddc6] bg-[#fffdf5] text-[#53636a] hover:border-[#263238]"}`}>Show all categories</button></div></section>

    <section className="paper-lines py-16 sm:py-24"><div className="container"><div className="flex flex-col gap-8"><div className="flex flex-col justify-between gap-7 lg:flex-row lg:items-end"><SectionHeading eyebrow="Find your level" title="Start where it feels right." text="Difficulty is a gentle guide, not a test. Age and grade filters are ready for real learning data when it is added." /><div className="flex flex-wrap gap-2">{difficultyOptions.map((difficulty) => <button key={difficulty} type="button" onClick={() => setSelectedDifficulty(difficulty)} aria-pressed={selectedDifficulty === difficulty} className={`rounded-full border px-4 py-2.5 text-sm font-900 transition-colors ${selectedDifficulty === difficulty ? "border-[#263238] bg-[#263238] text-[#fff9e8]" : "border-[#e8ddc6] bg-[#fffdf5] text-[#53636a] hover:border-[#263238]"}`}>{difficulty}</button>)}</div></div><div className="grid gap-3 sm:grid-cols-2"><label className="grid gap-2 text-xs font-900 uppercase tracking-[.12em] text-[#9b8b68]">Age<select value={selectedAge} onChange={(event) => setSelectedAge(event.target.value)} className="focus-ring min-h-12 rounded-xl border border-[#e8ddc6] bg-[#fffdf5] px-4 text-sm font-800 normal-case tracking-normal text-[#53636a]"><option>{ageOptions[0]}</option><option>{ageOptions[1]}</option></select></label><label className="grid gap-2 text-xs font-900 uppercase tracking-[.12em] text-[#9b8b68]">School grade<select value={selectedGrade} onChange={(event) => setSelectedGrade(event.target.value)} className="focus-ring min-h-12 rounded-xl border border-[#e8ddc6] bg-[#fffdf5] px-4 text-sm font-800 normal-case tracking-normal text-[#53636a]"><option>{gradeOptions[0]}</option><option>{gradeOptions[1]}</option></select></label></div></div><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{filteredGames.map((game) => <LearningGameCard key={game.name} game={game} />)}</div>{filteredGames.length === 0 && <div className="mt-10 rounded-2xl border border-dashed border-[#e8ddc6] bg-[#fffdf5]/70 p-10 text-center"><p className="font-[Fraunces] text-2xl">No games in this drawer yet.</p><p className="mt-2 text-sm text-[#6d7b80]">Try another category or level as the Learning Zone grows.</p></div>}</div></section>

    <section className="bg-[#263238] py-16 text-[#fff9e8] sm:py-24"><div className="container"><div className="grid gap-10 lg:grid-cols-[.75fr_1.25fr] lg:items-center"><div><p className="text-xs font-900 uppercase tracking-[.18em] text-[#f9d96b]">Your progress shelf</p><h2 className="mt-5 text-[clamp(2.5rem,5vw,4.8rem)] font-600 leading-[.95]">A place to keep <span className="text-[#f9d96b]">your wins.</span></h2><p className="mt-5 max-w-md text-base leading-7 text-[#fff9e8]/70">Progress tracking will arrive with accounts and real learning activities. For now, this is a friendly preview of what the shelf can hold.</p></div><div className="grid gap-3 sm:grid-cols-2"><ProgressPreview icon={<Check />} label="Games completed" /><ProgressPreview icon={<Star size={24} />} label="Points" /><ProgressPreview icon={<Trophy size={24} />} label="Badges" /><ProgressPreview icon={<PenLine size={24} />} label="Writing progress" /><ProgressPreview icon={<Sparkles size={24} />} label="Current level" /></div></div></div></section>

    <section className="py-16 sm:py-24"><div className="container grid gap-4 lg:grid-cols-2"><PreviewCard icon={<Feather size={24} />} eyebrow="Writing practice" title={writingPreview.title} text={writingPreview.text} items={writingPreview.activities} tone="bg-[#f9d96b]" /><PreviewCard icon={<Search size={24} />} eyebrow="Etymology" title={etymologyPreview.title} text={etymologyPreview.text} items={[etymologyPreview.note]} tone="bg-[#f4a261]" /></div></section>

    <section className="border-t border-[#e8ddc6] py-16 text-center sm:py-24"><div className="container"><span className="mx-auto grid h-12 w-12 place-items-center rounded-full bg-[#f9d96b] text-[#263238]"><LockKeyhole size={22} /></span><h2 className="mt-5 text-4xl font-600 sm:text-5xl">More to discover soon.</h2><p className="mx-auto mt-4 max-w-lg text-sm leading-7 text-[#6d7b80]">The Learning Zone is a UI foundation for now. Actual games, accounts, badges, points and writing feedback will be added in a later chapter.</p><Link href="/contact" className="mt-7 inline-flex items-center gap-2 rounded-full bg-[#263238] px-6 py-4 text-sm font-900 text-[#fff9e8] shadow-[4px_5px_0_#f58f82]">Ask about the circle <ArrowRight size={17} /></Link></div></section>
  </div>;
}

function ProgressPreview({ icon, label }: { icon: React.ReactNode; label: string }) { return <div className="rounded-2xl border border-[#fff9e8]/15 bg-[#fff9e8]/8 p-5 transition-colors hover:bg-[#fff9e8]/12"><div className="flex items-center justify-between text-[#f9d96b]"><span>{icon}</span><span className="rounded-full border border-[#fff9e8]/15 px-2.5 py-1 text-[.62rem] font-900 uppercase tracking-[.1em] text-[#fff9e8]/55">Preview</span></div><p className="mt-6 font-[Fraunces] text-xl">{label}</p><p className="mt-1 text-sm text-[#fff9e8]/55">Ready for your first activity</p></div>; }

function PreviewCard({ icon, eyebrow, title, text, items, tone }: { icon: React.ReactNode; eyebrow: string; title: string; text: string; items: string[]; tone: string }) { return <article className="story-card rounded-[1.65rem] p-6 sm:p-8"><div className="flex items-start justify-between gap-4"><span className={`grid h-12 w-12 place-items-center rounded-2xl ${tone} text-[#263238]`}>{icon}</span><span className="rounded-full bg-[#f5efdf] px-3 py-1.5 text-[.66rem] font-900 uppercase tracking-[.1em] text-[#8d8065]">Preview</span></div><p className="mt-7 text-xs font-900 uppercase tracking-[.16em] text-[#ef7e72]">{eyebrow}</p><h2 className="mt-2 font-[Fraunces] text-3xl font-600">{title}</h2><p className="mt-3 text-sm leading-7 text-[#6d7b80]">{text}</p><ul className="mt-6 grid gap-2 text-sm font-800 text-[#53636a]">{items.map((item) => <li key={item} className="flex items-center gap-2"><Check size={16} className="text-[#3d7042]" />{item}</li>)}</ul></article>; }
