import { ArrowRight, Check, Quote } from "lucide-react";
import { Link } from "wouter";
import { IconMark, MiniIcon, type IllustrationIcon } from "./Illustrations";
import type { Tone } from "../data/siteData";

const toneClasses: Record<Tone, string> = { butter: "bg-[#f9d96b]", sky: "bg-[#8fd3e8]", coral: "bg-[#f58f82]", leaf: "bg-[#8dbf8a]", orange: "bg-[#f4a261]", lavender: "bg-[#c7b7df]" };

export function SectionHeading({ eyebrow, title, text, align = "left", light = false }: { eyebrow?: string; title: string; text?: string; align?: "left" | "center"; light?: boolean }) {
  return <div className={`${align === "center" ? "mx-auto text-center" : ""} max-w-2xl`}><div className={`mb-4 flex items-center gap-3 text-[.7rem] font-900 uppercase tracking-[.19em] ${align === "center" ? "justify-center" : ""} ${light ? "text-[#f9d96b]" : "text-[#ef7e72]"}`}><span className="h-px w-7 bg-current" />{eyebrow ?? "The Lexicon Circle"}<span className="h-px w-7 bg-current" /></div><h2 className={`text-[clamp(2.25rem,5vw,4.2rem)] font-600 leading-[.98] ${light ? "text-[#fff9e8]" : "text-[#263238]"}`}>{title}</h2>{text && <p className={`mt-5 max-w-xl text-base leading-7 ${align === "center" ? "mx-auto" : ""} ${light ? "text-[#fff9e8]/75" : "text-[#6d7b80]"}`}>{text}</p>}</div>;
}

export function ProgramCard({ program, compact = false }: { program: { slug: string; title: string; eyebrow: string; age: string; text: string; icon: IllustrationIcon; tone: Tone }; compact?: boolean }) {
  return <article className={`group story-card flex h-full flex-col rounded-[1.65rem] p-5 transition-all duration-300 hover:-translate-y-1 hover:shadow-[0_25px_70px_rgba(74,66,45,.14)] ${compact ? "md:p-6" : "md:p-7"}`}><div className="flex items-start justify-between gap-3"><span className={`grid h-14 w-14 place-items-center rounded-[19px] ${toneClasses[program.tone]} text-[#263238] transition-transform duration-300 group-hover:rotate-[-8deg]`}><IconMark name={program.icon} size={27} /></span><span className="rounded-full bg-[#f5efdf] px-3 py-1.5 text-[.68rem] font-900 uppercase tracking-[.12em] text-[#7b786d]">{program.age}</span></div><p className="mt-7 text-[.7rem] font-900 uppercase tracking-[.16em] text-[#ef7e72]">{program.eyebrow}</p><h3 className="mt-2 font-[Fraunces] text-2xl font-600 leading-tight">{program.title}</h3><p className="mt-3 flex-1 text-sm leading-6 text-[#6d7b80]">{program.text}</p><Link href={`/programs/${program.slug}`} className="focus-ring mt-6 inline-flex w-fit items-center gap-2 rounded-lg text-sm font-900 text-[#263238] underline decoration-[#f9d96b] decoration-2 underline-offset-4 transition-all hover:gap-3">Explore <ArrowRight size={16} /></Link></article>;
}

export function DiscoveryCard({ item }: { item: { title: string; text: string; icon: IllustrationIcon; tone: Tone } }) { return <article className="group flex gap-4 rounded-2xl border border-[#e8ddc6] bg-[#fffdf5]/55 p-4 transition-all hover:-translate-y-1 hover:bg-[#fffdf5] hover:shadow-[0_16px_35px_rgba(74,66,45,.08)]"><MiniIcon name={item.icon} tone={item.tone} /><div><h3 className="font-[Fraunces] text-lg font-600">{item.title}</h3><p className="mt-1 text-sm leading-6 text-[#6d7b80]">{item.text}</p></div></article>; }

export function QuoteCard({ quote, label, note }: { quote: string; label: string; note?: string }) { return <article className="relative rounded-2xl border border-[#e8ddc6] bg-[#fffdf5] p-6"><Quote className="absolute right-5 top-5 text-[#f9d96b]" size={25} fill="currentColor" /><p className="pr-6 font-[Fraunces] text-xl leading-snug text-[#43545a]">“{quote}”</p><div className="mt-6 flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-full bg-[#f58f82] text-sm font-900 text-[#263238]">{label.slice(0, 1)}</span><div><p className="text-sm font-900">{label}</p>{note && <p className="text-xs text-[#8d8065]">{note}</p>}</div></div></article>; }

export function OutcomeList({ items }: { items: readonly string[] }) { return <ul className="grid gap-3">{items.map((item) => <li key={item} className="flex items-start gap-3 text-sm leading-6 text-[#53636a]"><span className="mt-1 grid h-5 w-5 shrink-0 place-items-center rounded-full bg-[#8dbf8a] text-[#263238]"><Check size={13} strokeWidth={3} /></span>{item}</li>)}</ul>; }
