import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, Check, RotateCcw, Sparkles } from "lucide-react";
import { Link } from "wouter";
import { SCORING_CONFIG, type GameQuestion, type PlayableGame } from "../data/learningGameData";
import { recordAttempt } from "../lib/learningProgress";

function normalise(value: string) { return value.trim().replace(/\s+/g, " ").replace(/[.!?]+$/, "").toUpperCase(); }
type Feedback = { tone: "good" | "try"; title: string; detail: string } | null;

export default function LearningGameEngine({ game }: { game: PlayableGame }) {
  const [questionIndex, setQuestionIndex] = useState(0);
  const [score, setScore] = useState(0);
  const [points, setPoints] = useState(0);
  const [selected, setSelected] = useState<string | null>(null);
  const [textAnswer, setTextAnswer] = useState("");
  const [builtIndexes, setBuiltIndexes] = useState<number[]>([]);
  const [feedback, setFeedback] = useState<Feedback>(null);
  const [complete, setComplete] = useState(false);
  const question = game.questions[questionIndex];
  const builtWord = useMemo(() => (question?.letters ?? []).filter((_, index) => builtIndexes.includes(index)).join(""), [question, builtIndexes]);
  useEffect(() => { if (complete) recordAttempt({ id: `${game.id}:completion`, gameId: game.id, score, points, completedAt: new Date().toISOString(), completed: true }); }, [complete, game.id, points, score]);
  if (!question) return <FallbackGameState />;

  const resetAnswer = () => { setSelected(null); setTextAnswer(""); setBuiltIndexes([]); setFeedback(null); };
  const isWriting = question.kind === "writing";
  const answerValue = question.kind === "letters" ? builtWord : question.kind === "choice" ? selected ?? "" : textAnswer;
  const canSubmit = Boolean(answerValue.trim()) && feedback?.tone !== "good";

  const checkAnswer = () => {
    if (!canSubmit) { if (!feedback) setFeedback({ tone: "try", title: "Choose an answer first.", detail: "Take a moment, then have another go." }); return; }
    const correct = isWriting ? answerValue.trim().split(/\s+/).length >= 1 : normalise(answerValue) === normalise(question.answer);
    if (correct) {
      const isLast = questionIndex === game.questions.length - 1;
      setScore((value) => value + 1);
      setPoints((value) => value + (isWriting ? SCORING_CONFIG.writingChallengePoints : SCORING_CONFIG.correctAnswerPoints) + (isLast ? SCORING_CONFIG.gameCompletionPoints : 0));
      setFeedback({ tone: "good", title: isWriting ? "Your story is on the page!" : "Great job!", detail: question.explanation ?? (isLast ? `You completed the game and earned a ${SCORING_CONFIG.gameCompletionPoints}-point completion bonus.` : "That answer fits beautifully.") });
    } else setFeedback({ tone: "try", title: "Almost! Let’s look again.", detail: question.explanation ?? "Look closely at the clues and try another answer." });
  };
  const nextQuestion = () => { if (feedback?.tone !== "good") return; if (questionIndex === game.questions.length - 1) setComplete(true); else { setQuestionIndex((value) => value + 1); resetAnswer(); } };
  const restart = () => { setQuestionIndex(0); setScore(0); setPoints(0); setComplete(false); resetAnswer(); };
  if (complete) return <GameComplete game={game} score={score} points={points} onRestart={restart} />;

  return <div className="mx-auto max-w-3xl rounded-[2rem] border border-[#e8ddc6] bg-[#fffdf5] p-5 shadow-[0_22px_60px_rgba(74,66,45,.10)] sm:p-8">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><Link href="/learning-zone" className="inline-flex items-center gap-2 text-sm font-900 text-[#6d7b80] hover:text-[#ef7e72]"><ArrowLeft size={16} /> Learning Zone</Link><div className="mt-5 flex flex-wrap items-center gap-2 text-[.68rem] font-900 uppercase tracking-[.14em] text-[#9b8b68]"><span>{game.category}</span><span>•</span><span>{game.difficulty}</span><span>•</span><span>{game.estimatedTime}</span></div><h1 className="mt-2 font-[Fraunces] text-4xl font-600 leading-tight sm:text-5xl">{game.name}</h1></div><span className="grid h-12 w-12 place-items-center rounded-[16px] bg-[#f9d96b] text-[#263238]"><Sparkles size={23} /></span></div>
    <p className="mt-5 rounded-2xl bg-[#f7efd9] p-4 text-sm leading-6 text-[#53636a]"><strong className="text-[#263238]">How to play:</strong> {game.instructions}</p>
    <div className="mt-8 flex items-center justify-between gap-4 text-xs font-900 uppercase tracking-[.12em] text-[#9b8b68]"><span>Question {questionIndex + 1} of {game.questions.length}</span><span>{points} points this round</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-[#f5efdf]"><div className="h-full rounded-full bg-[#ef7e72] transition-all duration-300" style={{ width: `${((questionIndex + (feedback?.tone === "good" ? 1 : 0)) / game.questions.length) * 100}%` }} /></div>
    <div key={question.id} className="quiz-step-enter mt-9"><p className="text-xs font-900 uppercase tracking-[.16em] text-[#ef7e72]">Your challenge</p><h2 className="mt-3 max-w-2xl font-[Fraunces] text-2xl font-600 leading-tight sm:text-3xl">{question.prompt}</h2>{question.display && <div className="mt-7 rounded-2xl bg-[#f7efd9] px-5 py-5 text-center font-[Fraunces] text-3xl font-600 tracking-[.12em] text-[#263238] sm:text-4xl">{question.display}</div>}
      {question.kind === "choice" ? <div className="mt-7 grid gap-3 sm:grid-cols-2">{question.options?.map((option) => <button type="button" key={option} disabled={feedback?.tone === "good"} onClick={() => setSelected(option)} aria-pressed={selected === option} className={`focus-ring min-h-14 rounded-2xl border px-4 py-3 text-left text-sm font-800 transition-all duration-200 hover:-translate-y-0.5 disabled:cursor-default ${selected === option ? "border-[#263238] bg-[#f9d96b]/55 shadow-[3px_3px_0_#263238]" : "border-[#e8ddc6] bg-[#fff9e8] hover:bg-[#f9d96b]/25"}`}>{option}</button>)}</div> : question.kind === "letters" ? <div className="mt-7"><div className="flex min-h-14 flex-wrap items-center gap-2 rounded-2xl border border-dashed border-[#e8ddc6] bg-[#fff9e8] p-3" aria-live="polite">{builtWord ? builtWord.split("").map((letter, index) => <span key={`${letter}-${index}`} className="grid h-10 w-10 place-items-center rounded-xl bg-[#8fd3e8] font-[Fraunces] text-xl font-600">{letter}</span>) : <span className="px-2 text-sm text-[#9b8b68]">Tap letters to build the word</span>}</div><div className="mt-4 flex flex-wrap gap-2">{question.letters?.map((letter, index) => <button type="button" key={`${letter}-${index}`} disabled={builtIndexes.includes(index) || feedback?.tone === "good"} onClick={() => setBuiltIndexes((values) => [...values, index])} className="focus-ring grid h-12 w-12 place-items-center rounded-xl border border-[#e8ddc6] bg-[#fffdf5] font-[Fraunces] text-xl font-600 transition-all hover:-translate-y-0.5 hover:bg-[#f9d96b]/55 disabled:opacity-35">{letter}</button>)}</div><button type="button" onClick={() => setBuiltIndexes([])} className="mt-3 text-xs font-900 text-[#6d7b80] underline">Reset letters</button></div> : isWriting ? <div className="mt-7"><textarea value={textAnswer} disabled={feedback?.tone === "good"} onChange={(event) => setTextAnswer(event.target.value)} aria-label="Write your response" placeholder="Start writing here…" rows={7} className="focus-ring w-full resize-y rounded-2xl border border-[#e8ddc6] bg-[#fff9e8] px-5 py-4 text-base leading-7 outline-none placeholder:text-[#9b8b68]" /><p className="mt-2 text-right text-xs font-800 text-[#9b8b68]">{textAnswer.trim() ? textAnswer.trim().split(/\s+/).length : 0} words</p></div> : <input value={textAnswer} disabled={feedback?.tone === "good"} onChange={(event) => setTextAnswer(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") checkAnswer(); }} aria-label="Type your answer" placeholder="Type your answer here" className="focus-ring mt-7 min-h-14 w-full rounded-2xl border border-[#e8ddc6] bg-[#fff9e8] px-5 text-base font-800 outline-none placeholder:font-500 placeholder:text-[#9b8b68]" />}</div>
    {feedback && <div className={`mt-7 rounded-2xl border p-4 ${feedback.tone === "good" ? "border-[#8dbf8a]/45 bg-[#8dbf8a]/18" : "border-[#f4a261]/45 bg-[#f4a261]/15"}`} role="status"><div className="flex items-start gap-3"><span className={`mt-0.5 grid h-7 w-7 shrink-0 place-items-center rounded-full ${feedback.tone === "good" ? "bg-[#8dbf8a]" : "bg-[#f4a261]"}`}>{feedback.tone === "good" ? <Check size={16} strokeWidth={3} /> : <Sparkles size={15} />}</span><div><p className="font-[Fraunces] text-xl font-600">{feedback.title}</p><p className="mt-1 text-sm leading-6 text-[#53636a]">{feedback.detail}</p></div></div></div>}
    <div className="mt-7 flex flex-col-reverse gap-3 sm:flex-row sm:items-center sm:justify-between"><Link href="/learning-zone" className="inline-flex items-center justify-center gap-2 rounded-full border-2 border-[#263238] px-5 py-3 text-sm font-900 transition-colors hover:bg-[#f9d96b]">Exit game</Link>{feedback?.tone === "good" ? <button type="button" onClick={nextQuestion} className="inline-flex items-center justify-center gap-2 rounded-full bg-[#263238] px-5 py-3 text-sm font-900 text-[#fff9e8] shadow-[3px_4px_0_#f58f82]">{questionIndex === game.questions.length - 1 ? "See my result" : "Next question"} <ArrowRight size={16} /></button> : <button type="button" onClick={checkAnswer} disabled={!answerValue.trim()} className="inline-flex items-center justify-center gap-2 rounded-full bg-[#263238] px-5 py-3 text-sm font-900 text-[#fff9e8] shadow-[3px_4px_0_#f58f82] transition-all hover:-translate-y-0.5 disabled:cursor-not-allowed disabled:opacity-45">Check answer <Check size={16} /></button>}</div>
  </div>;
}

function GameComplete({ game, score, points, onRestart }: { game: PlayableGame; score: number; points: number; onRestart: () => void }) { return <div className="mx-auto max-w-3xl rounded-[2rem] border border-[#e8ddc6] bg-[#fffdf5] p-8 text-center shadow-[0_22px_60px_rgba(74,66,45,.10)] sm:p-12"><span className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-[#8dbf8a] text-[#263238]"><Check size={29} strokeWidth={3} /></span><p className="mt-6 text-xs font-900 uppercase tracking-[.16em] text-[#ef7e72]">Game complete</p><h1 className="mt-3 font-[Fraunces] text-4xl font-600 sm:text-5xl">Well done!</h1><p className="mx-auto mt-4 max-w-md text-base leading-7 text-[#6d7b80]">You finished {game.name}. Your demo progress is kept for this browser session only.</p><div className="mx-auto mt-8 grid max-w-md grid-cols-2 gap-3"><div className="rounded-2xl bg-[#f7efd9] p-5"><p className="text-xs font-900 uppercase tracking-[.12em] text-[#9b8b68]">Score</p><p className="mt-2 font-[Fraunces] text-3xl font-600">{score}/{game.questions.length}</p></div><div className="rounded-2xl bg-[#f9d96b]/55 p-5"><p className="text-xs font-900 uppercase tracking-[.12em] text-[#9b8b68]">Points earned</p><p className="mt-2 font-[Fraunces] text-3xl font-600">{points}</p></div></div><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><Link href="/learning-zone/progress" className="inline-flex items-center justify-center gap-2 rounded-full border-2 border-[#263238] px-5 py-3 text-sm font-900 hover:bg-[#f9d96b]">View progress</Link><Link href="/learning-zone" className="inline-flex items-center justify-center gap-2 rounded-full border-2 border-[#263238] px-5 py-3 text-sm font-900 hover:bg-[#f9d96b]">Try another game</Link><button type="button" onClick={onRestart} className="inline-flex items-center justify-center gap-2 rounded-full bg-[#263238] px-5 py-3 text-sm font-900 text-[#fff9e8] shadow-[3px_4px_0_#f58f82]"><RotateCcw size={16} /> Play again</button></div></div>; }
function FallbackGameState() { return <div className="mx-auto max-w-2xl rounded-[2rem] border border-[#e8ddc6] bg-[#fffdf5] p-10 text-center"><h1 className="font-[Fraunces] text-3xl">Something went a little off track.</h1><p className="mt-3 text-sm text-[#6d7b80]">Please return to the Learning Zone and choose another game.</p><Link href="/learning-zone" className="mt-6 inline-flex rounded-full bg-[#263238] px-5 py-3 text-sm font-900 text-[#fff9e8]">Back to Learning Zone</Link></div>; }
